spring:
  profiles:
    include: secret, jwt # 파일 인식
#    active: dev # 파일 적용
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.SQL: debug
    org.example.springbootdeveloper: debug # org.example.springbootdeveloper 패키지와 하위 모든 클래스에 대해 DEBUG 레벨을 활성화
