spring:
  profiles:
    include: secret # 파일 인식
#    active: dev # 파일 적용
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.SQL: debug
