spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2.google.client-id}
            client-secret: ${oauth2.google.client-secret}
            scope:
              - email
              - profile
          naver:
            client-id: ${oauth2.naver.client-id}
            client-secret: ${oauth2.naver.client-secret}
            scope:
              - email
              - name
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-name: Naver

        provider: # 네이버의 provider는 등록되어 있지 않아 사용자가 등록해야 함
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 창
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰을 받는 URI
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 주소를 받는 URI
            user-name-attribute: response # 회원 벙보를 json 형태로 받는데 response라는 키값으로 네이버가 리턴해줌
