# worlflow 이름 지정
name: CI

# workflow가 시작될 조건 지정
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정
    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'  # 사용하고 있는 Java에 맞게 작성

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          JWT_ACCESS_EXPIRATION: ${{ secrets.JWT_ACCESS_EXPIRATION }}
          JWT_REFRESH_EXPIRATION: ${{  secrets.JWT_REFRESH_EXPIRATION  }}
          JWT_SECRET_KEY: ${{  secrets.JWT_SECRET_KEY  }}
          OAUTH2_GOOGLE_CLIENT_ID: ${{  secrets.OAUTH2_GOOGLE_CLIENT_ID  }}
          OAUTH2_GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET  }}
          OAUTH2_NAVER_CLIENT_ID: ${{  secrets.OAUTH2_NAVER_CLIENT_ID  }}
          OAUTH2_NAVER_CLIENT_SECRET: ${{  secrets.OAUTH2_NAVER_CLIENT_SECRET  }}
          SPRING_DATASOURCE_PASSWORD: ${{  secrets.SPRING_DATASOURCE_PASSWORD  }}
          SPRING_DATASOURCE_URL: ${{  secrets.SPRING_DATASOURCE_URL  }}
          SPRING_DATASOURCE_USERNAME: ${{  secrets.SPRING_DATASOURCE_USERNAME  }}
        run: ./gradlew clean build


